ALTER TABLE audit_events
    ADD COLUMN IF NOT EXISTS longitude     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS latitude      DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ip_address    VARCHAR(45),
    ADD COLUMN IF NOT EXISTS t2factor_used VARCHAR(20),
    ADD COLUMN IF NOT EXISTS signature     TEXT,
    ADD COLUMN IF NOT EXISTS metadata      JSONB;
